### ISSUE TITLE
Update Link synchronisation usage for Tidal 1.9

### ISSUE THREAD

**Issue by hellocatfood** [tidalcycles/tidal-doc#110]
Now that Link has been integrated into Tidal and will be releaseed in 1.9 ( https://github.com/tidalcycles/Tidal/issues/660 ) the usage instructions for using Link should be updated to reflect the new changes e.g no longer requiring Carabiner https://tidalcycles.org/docs/configuration/multiuser-tidal/#link-protocol-synchronization

**Comment by hellocatfood** [comment]
Thanks for linking to it! I've reviewed the changes and think they're great!

**Comment by yaxu** [comment]
Hey @Zalastax I still think there is something about quantum we're missing here.

> Ableton Link does not align beat/cycle values between session participants. Quoting [Link documentation](http://ableton.github.io/link/) "For example, beat 1 on one participant’s timeline might correspond to beat 3 or beat 4 on another’s, but it cannot correspond to beat 3.5". If aligned cycles is desired, use `resetcycles` in each Tidal instance simultaneously.

I think this is a misunderstanding. If you continue from that quote the next section is on phase alignment, which is for aligning cycles with quantum. 

There's a problem here that tidal doesn't deal with beats, but cycles (measures).. So where beat-driven software has bpm of 60 and quantum of 4, to match the cycles we want cps of 0.25 (i.e. cpm of 15). There is no quantum in tidal there is no concept of a fixed beat.

To convert to beatworld, we do need the quantum though. This is down to human judgement, because it depends on the time signature, and neither the link protocol or tidal care about that. Probably we want to set the quantum to be the same as whatever is in the other system, in the above case 4. Then we can convert to link's bpm by multiplying cps by the quantum * 60.

Probably a default of 4 is best, but it would be nice to have this configurable and ideally patternable..
